name: 'Prepare Doxygen'
description: 'An action to install Doxygen and graphviz on ubuntu'
runs:
  using: 'composite'
  steps:
    - name: Download and extract Doxygen
      run: |
        echo 'Download and extract Doxygen'
        wget -q https://www.doxygen.nl/files/doxygen-1.12.0.linux.bin.tar.gz
        mkdir temp
        tar -xzf doxygen-1.12.0.linux.bin.tar.gz -C ./temp
        cp ./temp/doxygen-1.12.0/bin/doxygen ./Docu/
        chmod +x ./Docu/doxygen
    - name: Install Graphviz
      run: |
        echo 'Get Graphviz'
        sudo apt-get -q install -y graphviz