name: genericplaybook
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  test-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Doxygen
      run: |
        echo 'download and extract doxygen'
        wget -q https://www.doxygen.nl/files/doxygen-1.12.0.linux.bin.tar.gz
        mkdir temp
        tar -xzf doxygen-1.12.0.linux.bin.tar.gz -C ./temp
        cp ./temp/doxygen-1.12.0/bin/doxygen ./Docu/
        chmod +x ./Docu/doxygen
        echo 'get graphviz'
        sudo apt-get -qq install -y graphviz
    
    - name: Get Versions
      run: |
        ./Docu/doxygen -v
        dot -V

    - name: Generate documentation and test
      run: |
        cd ./Docu
        ./doxygen ./Doxyfile > docuoutput.txt 2> docuerror.txt
        echo "------- start output stdout -----------"
        cat docuoutput.txt
        echo "------- end of output stdout ----------"
        echo "------- start output stderr -----------"
        cat docuerror.txt
        echo "------- end of output stderr ----------" 
        if [ -s docuerror.txt ]; then
          echo "Doxygen contained erroror warnings"
          exit 1
        else
          echo "Doxygen did not found error or warnings"
        fi