name: genericplaybook
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  test-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Doxygen
      uses: ./.github/actions/prepare-doxygen
    
    - name: Get Versions
      run: |
        ./Docu/doxygen -v
        dot -V

    - name: Generate documentation and test
      run: |
        cd ./Docu
        ./doxygen ./Doxyfile > docuoutput.txt 2> docuerror.txt
        echo "------- start output stdout -----------"
        cat docuoutput.txt
        echo "------- end of output stdout ----------"
        echo "------- start output stderr -----------"
        cat docuerror.txt
        echo "------- end of output stderr ----------" 
        if [ -s docuerror.txt ]; then
          echo "Doxygen contained erroror warnings"
          exit 1
        else
          echo "Doxygen did not found error or warnings"
        fi

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Docu/html