name: genericplaybook
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  test-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Doxygen
      run: sudo apt-get install -y doxygen graphviz ttf-freefont
    
    - name: Get Versions
      run: |
        doxygen -v
        dot -V

    - name: Generate documentation
      run: doxygen ./Docu/Doxyfile