name: genericplaybook
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  test-documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Doxygen
      run: |
        echo 'download and extract doxygen'
        wget -q https://www.doxygen.nl/files/doxygen-1.12.0.linux.bin.tar.gz
        mkdir temp
        tar -xzf doxygen-1.12.0.linux.bin.tar.gz -C ./temp
        cp ./temp/doxygen-1.12.0/bin/doxygen ./Docu/
        chmod +x ./Docu/doxygen
        echo 'get graphviz'
        sudo apt-get -qq install -y graphviz
    
    - name: Get Versions
      run: |
        ./Docu/doxygen -v
        dot -V

    - name: Generate documentation
      continue-on-error: true
      run: |
        cd ./Docu
        ./doxygen ./Doxyfile > docuoutput.txt
        echo "------- start output -----------"
        cat docuoutput.txt
        echo "------- end of output ----------"
        if grep -q "warning" docuoutput.txt; then
          echo "String 'warning' was found, failing the workflow."
          exit 1
        else
          echo "String 'warning' not found, passing the workflow."
        fi